[env:pro16MHzatmega328]
platform = atmelavr
framework = arduino
board = pro16MHzatmega328
board_build.mcu = atmega328p
board_build.f_cpu = 16000000L
lib_deps =
    https://github.com/mathertel/OneButton/archive/refs/tags/2.6.2.zip